# config.nu
#
# Sections mirror fish/.config/fish/config.fish and zsh/.zshrc; keep them in
# the same order with the same contents. shell-parity.sh reports drift.
#
# env vars and PATH live in env.nu, which nushell loads first.

# ===== tool init =====

# nushell cannot `source` a pipeline the way fish and zsh do, so both inits are
# generated by nu-regen-init.nu. Re-run it after upgrading either tool.
#
# starship lands in ~/.config/nushell/autoload/ and is picked up automatically.
# zoxide cannot: its defs and PWD hook do not take effect from an autoload dir,
# so it is generated next to this file and sourced by name. If nushell fails to
# start with "File not found", that generator has not been run on this machine.
source ~/.config/nushell/zoxide.nu

# ===== aliases: listing =====

# `ls`, `ll`, `la` and `lt` are deliberately NOT shadowed here: nushell's
# builtin ls returns structured data, and eza returns text, which would break
# every `ls | where ...` pipeline. The eza equivalents live under lz*.
alias lz = eza --color=always --icons=always
alias lzl = eza -al --group-directories-first --icons=always
alias lza = eza -a --color=always --group-directories-first --icons=always
# A `def`, not an alias: nushell mis-parses aliases whose body contains a pipe
# -- `| grep -v /` ended up handing eza a `-v`, which just printed its version.
def lf [] { eza -lf --color=always --icons=always | grep -v / }
alias lh = eza -dl .* --group-directories-first --icons=always
alias lzt = eza -al --sort=modified --icons=always
alias ld = eza -lD --icons=always
alias tree = eza --tree --color=always --icons=always

# ===== aliases: navigation =====

# These must be `def --env`, not aliases: nushell alias names cannot be `..`,
# and the cd has to affect the caller's environment.
def --env ".." [] { cd .. }
def --env "..." [] { cd ../.. }
def --env "...." [] { cd ../../.. }
def --env "....." [] { cd ../../../.. }
def --env "......" [] { cd ../../../../.. }

# ===== aliases: tools =====

alias g = git
alias v = nvim
alias vim = nvim
alias vid = neovide
alias code = ^code --password-store="gnome-libsecret"
alias c = code
alias y = yazi
# bat picks the theme up from $env.BAT_THEME, so the preview needs no --theme.
alias f = fzf --preview "bat {} --force-colorization"
alias neogit = nvim -c :Neogit
alias conf = tmuxinator start conf

# Pick a running container with fzf and open a shell in it. A script in
# scripts/, not three copies of a function: it is the same picker in all three
# shells, and the fzf preview has to be a command fzf can re-run per row.
alias dsh = docker-shell.sh

# Open a file, a URL or piped content in a real browser. A script for the same
# reason as dsh -- and because under WSL this is nowhere near a one-liner:
# explorer.exe has to be named with its full path and handed a windows path,
# which wslpath refuses to make from a relative one, i.e. from exactly what
# `fzf` prints. Takes targets or stdin: `br datei.html`, `fzf | br`.
alias br = browse.sh

alias cls = clear

# RDP to the Windows box. A `def` rather than an alias: nushell mis-parses an
# alias whose body contains a pipe. The password is piped in from 1Password
# rather than passed as /p:, which would leave it in shell history and in
# /proc/<pid>/cmdline for anything that can run ps.
def rdp [] { op read "op://Personal/My Microsoft Account/password" | xfreerdp3 /v:192.168.178.22 /d:MicrosoftAccount /u:michael-gawlik@outlook.com /from-stdin +dynamic-resolution +clipboard /cert:ignore }

# No `alias bat = batcat` here: on Arch the binary IS `bat`, so that aliased a
# working command to a missing one. fish bridges the name only when `bat` is
# genuinely absent and `batcat` present (Debian/Ubuntu).

# ===== aliases: system =====

# Named `sysupdate`, not `update`: `update` is a nushell builtin, and a `def`
# of that name shadows it for the whole file -- including anything `source`d
# here, which is what broke zoxide.nu (its init calls `update hooks ...`).
# Same reasoning as the ls/lz* split above. fish and zsh keep `update`; the
# divergence is recorded in scripts/.local/lib/dotfiles/shell-parity.allow.
#
# nushell has no `&&`, and `;` would run the upgrade even if the mirror
# refresh failed, so gate it on the exit code to match fish/zsh.
def sysupdate [] {
    sudo cachyos-rate-mirrors
    if $env.LAST_EXIT_CODE == 0 { sudo pacman -Syu }
}
alias mirror = sudo cachyos-rate-mirrors
def cleanup [] { sudo pacman -Rns ...(pacman -Qtdq | lines) }
alias jctl = journalctl -p 3 -xb
alias grubup = sudo grub-mkconfig -o /boot/grub/grub.cfg

# ===== functions =====

def --env ssh-agent-start [] {
    # `ssh-agent -c` emits csh syntax; parse the two setenv lines ourselves.
    ssh-agent -c
    | lines
    | parse "setenv {name} {value};"
    | reduce --fold {} {|it, acc| $acc | upsert $it.name $it.value }
    | load-env
    ssh-add ($nu.home-dir | path join ".ssh" "id_rsa")
}

# ===== shell-specific =====

$env.config.show_banner = false
$env.config.buffer_editor = "nvim"

# Legacy workaround for nushell#5585 (nushell scrolled on any keypress under
# WezTerm-on-WSL). This machine is niri on CachyOS, so it is very likely
# obsolete -- kept because turning it off is a behaviour change, not a fix.
$env.config.shell_integration.osc133 = false
